### ISSUE TITLE
Problem in installing

### ISSUE THREAD

**Issue by OrkoHunter** [dit/dit#85]
Hi there!

I just cloned the repository and tried `pip install` as suggested in the docs but it said `You must give at least one requirement to install (see "pip help install")`. I am on Linux.

Then I tried `sudo python setup.py install`. IMHO while manual installing, the second method is more favorable. Should we change the docs then?

Further I got some errors.
1. 
```
byte-compiling build/bdist.linux-x86_64/egg/dit/utils/tests/test_bindargs3.py to test_bindargs3.pyc
  File "build/bdist.linux-x86_64/egg/dit/utils/tests/test_bindargs3.py", line 5
    def F1(a, b, c=2, *, d, e, f=5, **kwargs):
                       ^
SyntaxError: invalid syntax
```

2.
```
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1425, in _get
    return self.loader.get_data(path)
zipimport.ZipImportError: bad local file header in /usr/local/lib/python2.7/dist-packages/dit-1.0.0.dev0-py2.7-linux-x86_64.egg
```

I checked out the `dit/utils/tests/test_bindargs3.py` code which had different arguments of the function F1 as reported here in `build/bdist.linux-x86_64/egg/dit/utils/tests/test_bindargs3.py`.

Even though I can successfully `import dit` in my python interpreter.

**Comment by chebee7i** [comment]
Thanks for the report. Will look into this.

**Comment by chebee7i** [comment]
Is it correct that you are using Python 2.7.x?

**Comment by chebee7i** [comment]
Regarding the `SyntaxError`. Unfortunately, this not easily fixed...but the error is harmless and you can ignore it.

The issue is that we have 2 versions of a file, one for 2.x and one for 3.x. When you install, Python tries to byte-compile both, even though the package will only use the correct one. It might be possible to fix this by modifying `package_data` in `setup.py` so that it only includes one of those Python files, but I think this would only fix `setup.py bdist`.  The source distribution (`setup.py sdist`) uses `MANIFEST.in`, and as far as I can tell, there is no way to conditionally include a file depending on the Python version (unless we manually generate our own `MANIFEST` file and forgo using `MANIFEST.in`).

**Comment by chebee7i** [comment]
So short of the missing ".", I think everything is good. I'll update the documentation to make it more clear to include the dot.

**Comment by OrkoHunter** [comment]
Yea. I didn't notice the dot there. Everything's good then.
